spring:
  application:
    name: recipeGenerator

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5433/food_nutrition_db}
    username: ${SPRING_R2DBC_USERNAME:food_nutrition_user}
    password: ${SPRING_R2DBC_PASSWORD:food_nutrition_pass}

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8080}
